onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/hpdcache_rsp_valid_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/hpdcache_req_valid_o
add wave -noupdate -subitemconfig {{/uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/i_frontend/fetch_entry_o[0]} -expand} /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/i_cva6_pipeline/i_frontend/fetch_entry_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/ypb_zcmt_rsp_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/ypb_zcmt_req_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/ypb_store_rsp_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/ypb_store_req_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/ypb_mmu_ptw_rsp_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/ypb_mmu_ptw_req_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/ypb_load_rsp_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/ypb_load_req_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/ypb_amo_rsp_o
add wave -noupdate -expand /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/ypb_amo_req_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/rst_ni
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/IsZcmtPort
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/IsMmuPtwPort
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/IsLoadPort
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/InvalidateOnFlush
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/HPDcacheCfg
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/hpdcache_rsp_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/hpdcache_req_tag_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/hpdcache_req_sid_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/hpdcache_req_ready_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/hpdcache_req_pma_o
add wave -noupdate -expand /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/hpdcache_req_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/hpdcache_req_is_uncacheable
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/hpdcache_req_abort_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/hpdcache_req
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/forward_store
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/forward_amo
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/CVA6Cfg
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/cva6_dcache_flush_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/cva6_dcache_flush_ack_o
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/clk_i
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/store_amo_gen/ypb_store_valid
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/store_amo_gen/ypb_amo_valid
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/store_amo_gen/store_data_size
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/store_amo_gen/hpdcache_req_store
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/store_amo_gen/hpdcache_req_flush
add wave -noupdate -expand /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/store_amo_gen/hpdcache_req_amo
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/store_amo_gen/forward_store
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/store_amo_gen/forward_flush
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/store_amo_gen/forward_amo
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/store_amo_gen/flush_fsm_q
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/store_amo_gen/flush_fsm_d
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/store_amo_gen/amo_resp_word
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/store_amo_gen/amo_pending_q
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/store_amo_gen/amo_op
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/store_amo_gen/amo_is_word_hi
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/store_amo_gen/amo_is_word
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/store_amo_gen/amo_data_size
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/store_amo_gen/amo_data_be
add wave -noupdate /uvmt_cva6_tb/cva6_dut_wrap/cva6_tb_wrapper_i/cva6_top/i_cva6/gen_cache_subsystem/i_cache_subsystem/i_dcache/i_cva6_hpdcache_store_if_adapter/store_amo_gen/amo_data
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {10672 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 265
configure wave -valuecolwidth 179
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {380 ns}
