// pll_90_phase.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module pll_90_phase (
		input  wire  refclk,     //     refclk.clk
		output wire  locked,     //     locked.export
		input  wire  rst,        //      reset.reset
		input  wire  permit_cal, // permit_cal.export
		output wire  outclk_0    //    outclk0.clk
	);

	pll_90_phase_altera_iopll_1931_u45xoyy iopll_0 (
		.refclk     (refclk),     //   input,  width = 1,     refclk.clk
		.locked     (locked),     //  output,  width = 1,     locked.export
		.rst        (rst),        //   input,  width = 1,      reset.reset
		.permit_cal (permit_cal), //   input,  width = 1, permit_cal.export
		.outclk_0   (outclk_0)    //  output,  width = 1,    outclk0.clk
	);

endmodule
