// hps.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module hps (
		inout  wire        intel_agilex_hps_0_hps_io_SDMMC_CMD,       //         intel_agilex_hps_0_hps_io.SDMMC_CMD
		inout  wire        intel_agilex_hps_0_hps_io_SDMMC_D0,        //                                  .SDMMC_D0
		inout  wire        intel_agilex_hps_0_hps_io_SDMMC_D1,        //                                  .SDMMC_D1
		inout  wire        intel_agilex_hps_0_hps_io_SDMMC_D2,        //                                  .SDMMC_D2
		inout  wire        intel_agilex_hps_0_hps_io_SDMMC_D3,        //                                  .SDMMC_D3
		output wire        intel_agilex_hps_0_hps_io_SDMMC_CCLK,      //                                  .SDMMC_CCLK
		output wire        intel_agilex_hps_0_h2f_reset_reset,        //      intel_agilex_hps_0_h2f_reset.reset
		input  wire        intel_agilex_hps_0_h2f_axi_clock_clk,      //  intel_agilex_hps_0_h2f_axi_clock.clk
		input  wire        intel_agilex_hps_0_h2f_axi_reset_reset_n,  //  intel_agilex_hps_0_h2f_axi_reset.reset_n
		output wire [3:0]  intel_agilex_hps_0_h2f_axi_master_awid,    // intel_agilex_hps_0_h2f_axi_master.awid
		output wire [31:0] intel_agilex_hps_0_h2f_axi_master_awaddr,  //                                  .awaddr
		output wire [7:0]  intel_agilex_hps_0_h2f_axi_master_awlen,   //                                  .awlen
		output wire [2:0]  intel_agilex_hps_0_h2f_axi_master_awsize,  //                                  .awsize
		output wire [1:0]  intel_agilex_hps_0_h2f_axi_master_awburst, //                                  .awburst
		output wire        intel_agilex_hps_0_h2f_axi_master_awlock,  //                                  .awlock
		output wire [3:0]  intel_agilex_hps_0_h2f_axi_master_awcache, //                                  .awcache
		output wire [2:0]  intel_agilex_hps_0_h2f_axi_master_awprot,  //                                  .awprot
		output wire        intel_agilex_hps_0_h2f_axi_master_awvalid, //                                  .awvalid
		input  wire        intel_agilex_hps_0_h2f_axi_master_awready, //                                  .awready
		output wire [63:0] intel_agilex_hps_0_h2f_axi_master_wdata,   //                                  .wdata
		output wire [7:0]  intel_agilex_hps_0_h2f_axi_master_wstrb,   //                                  .wstrb
		output wire        intel_agilex_hps_0_h2f_axi_master_wlast,   //                                  .wlast
		output wire        intel_agilex_hps_0_h2f_axi_master_wvalid,  //                                  .wvalid
		input  wire        intel_agilex_hps_0_h2f_axi_master_wready,  //                                  .wready
		input  wire [3:0]  intel_agilex_hps_0_h2f_axi_master_bid,     //                                  .bid
		input  wire [1:0]  intel_agilex_hps_0_h2f_axi_master_bresp,   //                                  .bresp
		input  wire        intel_agilex_hps_0_h2f_axi_master_bvalid,  //                                  .bvalid
		output wire        intel_agilex_hps_0_h2f_axi_master_bready,  //                                  .bready
		output wire [3:0]  intel_agilex_hps_0_h2f_axi_master_arid,    //                                  .arid
		output wire [31:0] intel_agilex_hps_0_h2f_axi_master_araddr,  //                                  .araddr
		output wire [7:0]  intel_agilex_hps_0_h2f_axi_master_arlen,   //                                  .arlen
		output wire [2:0]  intel_agilex_hps_0_h2f_axi_master_arsize,  //                                  .arsize
		output wire [1:0]  intel_agilex_hps_0_h2f_axi_master_arburst, //                                  .arburst
		output wire        intel_agilex_hps_0_h2f_axi_master_arlock,  //                                  .arlock
		output wire [3:0]  intel_agilex_hps_0_h2f_axi_master_arcache, //                                  .arcache
		output wire [2:0]  intel_agilex_hps_0_h2f_axi_master_arprot,  //                                  .arprot
		output wire        intel_agilex_hps_0_h2f_axi_master_arvalid, //                                  .arvalid
		input  wire        intel_agilex_hps_0_h2f_axi_master_arready, //                                  .arready
		input  wire [3:0]  intel_agilex_hps_0_h2f_axi_master_rid,     //                                  .rid
		input  wire [63:0] intel_agilex_hps_0_h2f_axi_master_rdata,   //                                  .rdata
		input  wire [1:0]  intel_agilex_hps_0_h2f_axi_master_rresp,   //                                  .rresp
		input  wire        intel_agilex_hps_0_h2f_axi_master_rlast,   //                                  .rlast
		input  wire        intel_agilex_hps_0_h2f_axi_master_rvalid,  //                                  .rvalid
		output wire        intel_agilex_hps_0_h2f_axi_master_rready   //                                  .rready
	);

	hps_intel_agilex_hps_0 intel_agilex_hps_0 (
		.SDMMC_CMD     (intel_agilex_hps_0_hps_io_SDMMC_CMD),       //   inout,   width = 1,         hps_io.SDMMC_CMD
		.SDMMC_D0      (intel_agilex_hps_0_hps_io_SDMMC_D0),        //   inout,   width = 1,               .SDMMC_D0
		.SDMMC_D1      (intel_agilex_hps_0_hps_io_SDMMC_D1),        //   inout,   width = 1,               .SDMMC_D1
		.SDMMC_D2      (intel_agilex_hps_0_hps_io_SDMMC_D2),        //   inout,   width = 1,               .SDMMC_D2
		.SDMMC_D3      (intel_agilex_hps_0_hps_io_SDMMC_D3),        //   inout,   width = 1,               .SDMMC_D3
		.SDMMC_CCLK    (intel_agilex_hps_0_hps_io_SDMMC_CCLK),      //  output,   width = 1,               .SDMMC_CCLK
		.h2f_rst       (intel_agilex_hps_0_h2f_reset_reset),        //  output,   width = 1,      h2f_reset.reset
		.h2f_axi_clk   (intel_agilex_hps_0_h2f_axi_clock_clk),      //   input,   width = 1,  h2f_axi_clock.clk
		.h2f_axi_rst_n (intel_agilex_hps_0_h2f_axi_reset_reset_n),  //   input,   width = 1,  h2f_axi_reset.reset_n
		.h2f_AWID      (intel_agilex_hps_0_h2f_axi_master_awid),    //  output,   width = 4, h2f_axi_master.awid
		.h2f_AWADDR    (intel_agilex_hps_0_h2f_axi_master_awaddr),  //  output,  width = 32,               .awaddr
		.h2f_AWLEN     (intel_agilex_hps_0_h2f_axi_master_awlen),   //  output,   width = 8,               .awlen
		.h2f_AWSIZE    (intel_agilex_hps_0_h2f_axi_master_awsize),  //  output,   width = 3,               .awsize
		.h2f_AWBURST   (intel_agilex_hps_0_h2f_axi_master_awburst), //  output,   width = 2,               .awburst
		.h2f_AWLOCK    (intel_agilex_hps_0_h2f_axi_master_awlock),  //  output,   width = 1,               .awlock
		.h2f_AWCACHE   (intel_agilex_hps_0_h2f_axi_master_awcache), //  output,   width = 4,               .awcache
		.h2f_AWPROT    (intel_agilex_hps_0_h2f_axi_master_awprot),  //  output,   width = 3,               .awprot
		.h2f_AWVALID   (intel_agilex_hps_0_h2f_axi_master_awvalid), //  output,   width = 1,               .awvalid
		.h2f_AWREADY   (intel_agilex_hps_0_h2f_axi_master_awready), //   input,   width = 1,               .awready
		.h2f_WDATA     (intel_agilex_hps_0_h2f_axi_master_wdata),   //  output,  width = 64,               .wdata
		.h2f_WSTRB     (intel_agilex_hps_0_h2f_axi_master_wstrb),   //  output,   width = 8,               .wstrb
		.h2f_WLAST     (intel_agilex_hps_0_h2f_axi_master_wlast),   //  output,   width = 1,               .wlast
		.h2f_WVALID    (intel_agilex_hps_0_h2f_axi_master_wvalid),  //  output,   width = 1,               .wvalid
		.h2f_WREADY    (intel_agilex_hps_0_h2f_axi_master_wready),  //   input,   width = 1,               .wready
		.h2f_BID       (intel_agilex_hps_0_h2f_axi_master_bid),     //   input,   width = 4,               .bid
		.h2f_BRESP     (intel_agilex_hps_0_h2f_axi_master_bresp),   //   input,   width = 2,               .bresp
		.h2f_BVALID    (intel_agilex_hps_0_h2f_axi_master_bvalid),  //   input,   width = 1,               .bvalid
		.h2f_BREADY    (intel_agilex_hps_0_h2f_axi_master_bready),  //  output,   width = 1,               .bready
		.h2f_ARID      (intel_agilex_hps_0_h2f_axi_master_arid),    //  output,   width = 4,               .arid
		.h2f_ARADDR    (intel_agilex_hps_0_h2f_axi_master_araddr),  //  output,  width = 32,               .araddr
		.h2f_ARLEN     (intel_agilex_hps_0_h2f_axi_master_arlen),   //  output,   width = 8,               .arlen
		.h2f_ARSIZE    (intel_agilex_hps_0_h2f_axi_master_arsize),  //  output,   width = 3,               .arsize
		.h2f_ARBURST   (intel_agilex_hps_0_h2f_axi_master_arburst), //  output,   width = 2,               .arburst
		.h2f_ARLOCK    (intel_agilex_hps_0_h2f_axi_master_arlock),  //  output,   width = 1,               .arlock
		.h2f_ARCACHE   (intel_agilex_hps_0_h2f_axi_master_arcache), //  output,   width = 4,               .arcache
		.h2f_ARPROT    (intel_agilex_hps_0_h2f_axi_master_arprot),  //  output,   width = 3,               .arprot
		.h2f_ARVALID   (intel_agilex_hps_0_h2f_axi_master_arvalid), //  output,   width = 1,               .arvalid
		.h2f_ARREADY   (intel_agilex_hps_0_h2f_axi_master_arready), //   input,   width = 1,               .arready
		.h2f_RID       (intel_agilex_hps_0_h2f_axi_master_rid),     //   input,   width = 4,               .rid
		.h2f_RDATA     (intel_agilex_hps_0_h2f_axi_master_rdata),   //   input,  width = 64,               .rdata
		.h2f_RRESP     (intel_agilex_hps_0_h2f_axi_master_rresp),   //   input,   width = 2,               .rresp
		.h2f_RLAST     (intel_agilex_hps_0_h2f_axi_master_rlast),   //   input,   width = 1,               .rlast
		.h2f_RVALID    (intel_agilex_hps_0_h2f_axi_master_rvalid),  //   input,   width = 1,               .rvalid
		.h2f_RREADY    (intel_agilex_hps_0_h2f_axi_master_rready)   //  output,   width = 1,               .rready
	);

endmodule
